[package]
name = "sn0int"
version = "0.9.1"
description = "Semi-automatic OSINT framework and package manager"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sn0int"
categories = ["command-line-utilities"]
readme = "README.md"
edition = "2018"

[profile.release]
# skip lto to avoid compiler bug:
# https://github.com/kpcyrd/sn0int/issues/77
# https://github.com/rust-lang/rust/issues/58674
opt-level = 0
lto = false

[badges]
travis-ci = { repository = "kpcyrd/sn0int" }

[workspace]
members = ["sn0int-registry/sn0int-common",
           "sn0int-registry"]

[dependencies]
sn0int-common = { version="0.4.0", path="sn0int-registry/sn0int-common" }
rustyline = "3"
log = "0.4"
env_logger = "0.6"
hlua-badtouch = "0.4"
structopt = "0.2"
failure = "0.1"
rand = "0.6"
colored = "1.6"
lazy_static = "1.0"
shellwords = "1.0"
publicsuffix = { version="1.5", default-features=false }
diesel = { version = "1.0.0", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "1.0"
url = "1.7"
#chrootable-https = { path = "../chrootable-https" }
chrootable-https = "0.8"
base64 = "0.10"
kuchiki = "0.7.2"
serde_urlencoded = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam-channel = "0.3"
ctrlc = "3.1"
opener = "0.3.0"
separator = "0.4"
maplit = "1.0.1"
sloppy-rfc4880 = "0.1.2"
regex = "1.0"
toml = "0.4"
maxminddb = "0.13"
tar = "0.4.17"
libflate = "0.1.14"
threadpool = "1.7"
x509-parser = "0.4.0"
der-parser = "1.1.0"
nom = "4.1.1"
atty = "0.2"
bufstream = "0.1.4"
tokio = "0.1.14"
semver = "0.9"

[target.'cfg(target_os="linux")'.dependencies]
caps = "0.3"
#syscallz = { path="../syscallz-rs" }
syscallz = "0.11"
nix = "0.13"

[target.'cfg(target_os="openbsd")'.dependencies]
pledge = "0.3.1"
unveil = "0.2.0"

[dev-dependencies]
#boxxy = { path = "../boxxy-rs" }
boxxy = "0.8"
